# Generated by Django 4.2.24 on 2025-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0002_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub1", models.IntegerField()),
                ("sub2", models.IntegerField()),
                ("sub3", models.IntegerField()),
                ("sub4", models.IntegerField()),
                ("sub5", models.IntegerField()),
                ("total", models.IntegerField()),
                ("average", models.FloatField()),
                ("result", models.BooleanField()),
            ],
        ),
    ]
