# Generated by Django 4.2.24 on 2025-10-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0003_ranksheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="schoolapp.student",
            ),
        ),
    ]
