# Generated by Django 4.2.24 on 2025-10-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_classroom_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="teacher.subject",
            ),
        ),
    ]
