# Generated by Django 4.2.24 on 2025-10-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_classroom_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("experience", models.IntegerField(blank=True, null=True)),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
    ]
